import type {
  AnalyticsMetric,
  AppSettings,
  Call,
  Contact,
  DemoScenario,
  LanguageDistribution,
  Notification,
  RiskEvent,
  SignalDistribution,
} from '../types';

export const INITIAL_SETTINGS: AppSettings = {
  account: {
    fullName: 'Aaryaman Singh',
    email: 'aaryaman@aureliax.ai',
    organization: 'AureliaX Security Operations',
  },
  language: {
    interfaceLanguage: 'English',
    enabledAnalysisLanguages: [
      'Hindi',
      'Punjabi',
      'Gujarati',
      'Kannada',
      'Tamil',
      'Telugu',
      'English',
      'German',
      'Japanese',
    ],
  },
  notifications: {
    highRiskAlerts: true,
    suspiciousCallAlerts: true,
    verificationRequests: true,
    emailNotifications: true,
  },
  security: {
    mfaEnabled: true,
    sessionTimeoutMinutes: 30,
  },
  privacy: {
    audioRetentionDays: 90,
    transcriptRetentionDays: 180,
    allowDataProcessing: true,
  },
  ai: {
    riskSensitivity: 'HIGH',
    alertThreshold: 70,
    speakerVerificationThreshold: 75,
    realtimeAnalysisMode: true,
  },
};

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'demo-hindi-scam',
    name: 'Hindi Voice Cloning Bank Scam',
    description: 'Impersonation attack using deepfake neural voice clone of bank executive requesting urgent OTP transfer.',
    language: 'Hindi',
    expectedRiskLevel: 'HIGH_RISK',
    expectedRiskScore: 92,
    keySignals: ['Synthetic spectral artifact', 'Flat pitch contour', 'Abrupt hesitation pause'],
  },
  {
    id: 'demo-punjabi-family',
    name: 'Punjabi Emergency Distress Call',
    description: 'Voice verification of family emergency claim with natural emotion and prosodic consistency.',
    language: 'Punjabi',
    expectedRiskLevel: 'SAFE',
    expectedRiskScore: 12,
    keySignals: ['High speaker similarity', 'Natural emotional variation', 'Expected pause rhythm'],
  },
  {
    id: 'demo-english-exec',
    name: 'English CEO Financial Fraud',
    description: 'AI-generated voice clone demanding immediate wire transfer to unverified vendor account.',
    language: 'English',
    expectedRiskLevel: 'HIGH_RISK',
    expectedRiskScore: 88,
    keySignals: ['94% Synthetic voice probability', 'Voice signature mismatch', 'High turn-taking latency'],
  },
  {
    id: 'demo-gujarati-otp',
    name: 'Gujarati Credential Verification',
    description: 'Suspicious call displaying moderate pause anomalies and boundary tone glitches.',
    language: 'Gujarati',
    expectedRiskLevel: 'SUSPICIOUS',
    expectedRiskScore: 58,
    keySignals: ['Moderate spectral distortion', 'Unusual pause duration', 'Verification recommended'],
  },
  {
    id: 'demo-kannada-support',
    name: 'Kannada Customer Support Call',
    description: 'Verified inbound customer inquiry with high speaker match score.',
    language: 'Kannada',
    expectedRiskLevel: 'SAFE',
    expectedRiskScore: 18,
    keySignals: ['Verified acoustic fingerprint', 'Natural intonation', 'Safe recommendation'],
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'cnt-1',
    name: 'Rajesh Sharma',
    phone: '+91 98765 43210',
    email: 'rajesh.sharma@nexusbank.in',
    organization: 'Nexus Financial Group',
    trustStatus: 'TRUSTED',
    voiceProfileStatus: 'ENROLLED',
    lastInteraction: '2026-09-07 10:15',
    riskHistory: [
      { date: '2026-08-10', riskScore: 14 },
      { date: '2026-08-25', riskScore: 10 },
      { date: '2026-09-07', riskScore: 12 },
    ],
    totalCalls: 18,
    createdAt: '2026-05-12',
  },
  {
    id: 'cnt-2',
    name: 'Harpreet Kaur',
    phone: '+91 98123 76543',
    email: 'harpreet.k@punjabtech.org',
    organization: 'Punjab Tech Systems',
    trustStatus: 'TRUSTED',
    voiceProfileStatus: 'ENROLLED',
    lastInteraction: '2026-09-06 16:40',
    riskHistory: [
      { date: '2026-08-01', riskScore: 18 },
      { date: '2026-09-06', riskScore: 15 },
    ],
    totalCalls: 9,
    createdAt: '2026-06-20',
  },
  {
    id: 'cnt-3',
    name: 'Vikram Patel',
    phone: '+91 97234 11890',
    email: 'vikram@patel-imports.com',
    organization: 'Patel International',
    trustStatus: 'NEUTRAL',
    voiceProfileStatus: 'PENDING',
    lastInteraction: '2026-09-05 14:20',
    riskHistory: [{ date: '2026-09-05', riskScore: 54 }],
    totalCalls: 3,
    createdAt: '2026-09-01',
  },
  {
    id: 'cnt-4',
    name: 'Unknown Caller #9842',
    phone: '+91 99001 88219',
    organization: 'Unverified Entity',
    trustStatus: 'BLOCKED',
    voiceProfileStatus: 'NONE',
    lastInteraction: '2026-09-07 11:02',
    riskHistory: [{ date: '2026-09-07', riskScore: 94 }],
    totalCalls: 1,
    createdAt: '2026-09-07',
  },
  {
    id: 'cnt-5',
    name: 'Siddharth Rao',
    phone: '+91 94450 33112',
    email: 'siddharth@bluru-ventures.io',
    organization: 'Bluru Ventures',
    trustStatus: 'TRUSTED',
    voiceProfileStatus: 'ENROLLED',
    lastInteraction: '2026-09-04 11:30',
    riskHistory: [
      { date: '2026-07-15', riskScore: 22 },
      { date: '2026-09-04', riskScore: 19 },
    ],
    totalCalls: 12,
    createdAt: '2026-04-10',
  },
];

export const MOCK_CALLS: Call[] = [
  {
    id: 'call-101',
    caller: 'Unknown Caller #9842',
    callerPhone: '+91 99001 88219',
    contactId: 'cnt-4',
    startTime: '2026-09-07 11:02:15',
    endTime: '2026-09-07 11:04:45',
    duration: 150,
    language: 'Hindi',
    audioSource: 'MICROPHONE',
    riskScore: 92,
    riskLevel: 'HIGH_RISK',
    voiceIntegrity: 8,
    status: 'BLOCKED',
    analysisId: 'an-101',
    analysis: {
      id: 'an-101',
      callId: 'call-101',
      timestamp: '2026-09-07 11:02:15',
      syntheticProbability: 94,
      speakerSimilarity: 12,
      emotion: 'Stressed',
      emotionalConsistency: 35,
      prosodyScore: 28,
      pitchVariation: 22,
      speakingRate: 85,
      vocalEnergy: 70,
      rhythm: 30,
      stressPattern: 40,
      hesitationIndex: 78,
      pauseAnomaly: 'HIGH',
      pauseFrequency: 14,
      avgPauseDuration: 1850,
      abruptPauses: 6,
      temporalConsistency: 42,
      avgResponseLatency: 1450,
      turnTakingConsistency: 38,
      detectedLanguage: 'Hindi',
      languageConfidence: 98,
      overallRiskScore: 92,
      riskLevel: 'HIGH_RISK',
      riskFactors: [
        'High synthetic voice neural model signature (94%)',
        'Abrupt cadence pauses & acoustic phase artifacts',
        'Speaker voice embedding does not match enrolled profile',
        'Urgent financial transfer framing detected',
      ],
      recommendation: 'END_CALL',
      recommendationReason: 'Extremely high likelihood of AI-generated synthetic voice clone scam.',
    },
    transcript: [
      {
        id: 'tr-1',
        timestamp: '00:05',
        speaker: 'CALLER',
        text: 'नमस्ते, मैं आपके बैंक के सुरक्षा विभाग से बात कर रहा हूँ।',
        isSuspicious: false,
      },
      {
        id: 'tr-2',
        timestamp: '00:18',
        speaker: 'CALLER',
        text: 'आपके खाते में संदिग्ध गतिविधि पाई गई है। तुरंत ओटीपी सांझा करें।',
        isSuspicious: true,
        anomalyNote: 'Synthetic neural artifact detected in phrase transition',
      },
      {
        id: 'tr-3',
        timestamp: '00:32',
        speaker: 'AGENT',
        text: 'कृपया अपना कर्मचारी आईडी बताएं।',
        isSuspicious: false,
      },
      {
        id: 'tr-4',
        timestamp: '00:45',
        speaker: 'CALLER',
        text: 'समय नहीं है, खाता तुरंत ब्लॉक हो जाएगा। अभी ओटीपी दें।',
        isSuspicious: true,
        anomalyNote: 'Abrupt pause anomaly and unnatural pitch flattening',
      },
    ],
    tags: ['Impersonation', 'Bank Scam', 'Hindi Deepfake'],
  },
  {
    id: 'call-102',
    caller: 'Rajesh Sharma',
    callerPhone: '+91 98765 43210',
    contactId: 'cnt-1',
    startTime: '2026-09-07 10:15:00',
    endTime: '2026-09-07 10:18:20',
    duration: 200,
    language: 'Hindi',
    audioSource: 'UPLOAD',
    riskScore: 12,
    riskLevel: 'SAFE',
    voiceIntegrity: 96,
    status: 'COMPLETED',
    analysisId: 'an-102',
    analysis: {
      id: 'an-102',
      callId: 'call-102',
      timestamp: '2026-09-07 10:15:00',
      syntheticProbability: 4,
      speakerSimilarity: 96,
      emotion: 'Calm',
      emotionalConsistency: 92,
      prosodyScore: 89,
      pitchVariation: 84,
      speakingRate: 65,
      vocalEnergy: 68,
      rhythm: 88,
      stressPattern: 85,
      hesitationIndex: 12,
      pauseAnomaly: 'LOW',
      pauseFrequency: 5,
      avgPauseDuration: 620,
      abruptPauses: 0,
      temporalConsistency: 94,
      avgResponseLatency: 480,
      turnTakingConsistency: 92,
      detectedLanguage: 'Hindi',
      languageConfidence: 96,
      overallRiskScore: 12,
      riskLevel: 'SAFE',
      riskFactors: [],
      recommendation: 'CONTINUE',
      recommendationReason: 'Authentic acoustic profile matching enrolled voice signature.',
    },
    transcript: [
      {
        id: 'tr-10',
        timestamp: '00:04',
        speaker: 'CALLER',
        text: 'गुड मॉर्निंग आर्यमन, क्या हमने आज की बोर्ड मीटिंग का प्रेजेंटेशन फाइनल कर लिया?',
        isSuspicious: false,
      },
      {
        id: 'tr-11',
        timestamp: '00:20',
        speaker: 'AGENT',
        text: 'हाँ राजेश जी, फाइलें अपडेट कर दी गई हैं।',
        isSuspicious: false,
      },
    ],
    tags: ['Verified Speaker', 'Internal Operations'],
  },
  {
    id: 'call-103',
    caller: 'Vikram Patel',
    callerPhone: '+91 97234 11890',
    contactId: 'cnt-3',
    startTime: '2026-09-05 14:20:10',
    endTime: '2026-09-05 14:24:00',
    duration: 230,
    language: 'Gujarati',
    audioSource: 'API',
    riskScore: 58,
    riskLevel: 'SUSPICIOUS',
    voiceIntegrity: 62,
    status: 'COMPLETED',
    analysisId: 'an-103',
    analysis: {
      id: 'an-103',
      callId: 'call-103',
      timestamp: '2026-09-05 14:20:10',
      syntheticProbability: 48,
      speakerSimilarity: 55,
      emotion: 'Uncertain',
      emotionalConsistency: 60,
      prosodyScore: 58,
      pitchVariation: 52,
      speakingRate: 72,
      vocalEnergy: 60,
      rhythm: 55,
      stressPattern: 58,
      hesitationIndex: 45,
      pauseAnomaly: 'MEDIUM',
      pauseFrequency: 9,
      avgPauseDuration: 1100,
      abruptPauses: 3,
      temporalConsistency: 64,
      avgResponseLatency: 950,
      turnTakingConsistency: 68,
      detectedLanguage: 'Gujarati',
      languageConfidence: 91,
      overallRiskScore: 58,
      riskLevel: 'SUSPICIOUS',
      riskFactors: [
        'Moderate acoustic spectral jitter detected',
        'Voice profile pending enrollment verification',
        'Slightly elevated latency before key technical responses',
      ],
      recommendation: 'VERIFY_CALLER',
      recommendationReason: 'Prosody inconsistency detected. Request secondary out-of-band verification.',
    },
    transcript: [
      {
        id: 'tr-20',
        timestamp: '00:08',
        speaker: 'CALLER',
        text: 'નમસ્તે, હું ઈમ્પોર્ટ કસ્ટમ્સ ડ્યુટી ચૂકવણી માટે વાત કરી રહ્યો છું.',
        isSuspicious: false,
      },
      {
        id: 'tr-21',
        timestamp: '00:35',
        speaker: 'CALLER',
        text: 'તમારે આજે જ બેંક ખાતાની વિગતો કન્ફર્મ કરવી પડશે.',
        isSuspicious: true,
        anomalyNote: 'Moderate pitch phase variation detected',
      },
    ],
    tags: ['Vendor Inquiry', 'Gujarati', 'Suspicious Prosody'],
  },
  {
    id: 'call-104',
    caller: 'Harpreet Kaur',
    callerPhone: '+91 98123 76543',
    contactId: 'cnt-2',
    startTime: '2026-09-06 16:40:00',
    endTime: '2026-09-06 16:42:30',
    duration: 150,
    language: 'Punjabi',
    audioSource: 'MICROPHONE',
    riskScore: 15,
    riskLevel: 'SAFE',
    voiceIntegrity: 95,
    status: 'COMPLETED',
    analysisId: 'an-104',
    analysis: {
      id: 'an-104',
      callId: 'call-104',
      timestamp: '2026-09-06 16:40:00',
      syntheticProbability: 5,
      speakerSimilarity: 95,
      emotion: 'Happy',
      emotionalConsistency: 94,
      prosodyScore: 91,
      pitchVariation: 88,
      speakingRate: 68,
      vocalEnergy: 75,
      rhythm: 92,
      stressPattern: 88,
      hesitationIndex: 10,
      pauseAnomaly: 'LOW',
      pauseFrequency: 4,
      avgPauseDuration: 550,
      abruptPauses: 0,
      temporalConsistency: 96,
      avgResponseLatency: 420,
      turnTakingConsistency: 95,
      detectedLanguage: 'Punjabi',
      languageConfidence: 97,
      overallRiskScore: 15,
      riskLevel: 'SAFE',
      riskFactors: [],
      recommendation: 'CONTINUE',
      recommendationReason: 'High speaker match score with authentic emotional dynamic range.',
    },
    transcript: [
      {
        id: 'tr-30',
        timestamp: '00:03',
        speaker: 'CALLER',
        text: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ! ਸਾਡਾ ਨਵਾਂ ਸੌਫਟਵੇਅਰ ਰਿਲੀਜ਼ ਤਿਆਰ ਹੈ।',
        isSuspicious: false,
      },
    ],
    tags: ['Punjabi Tech', 'Enrolled Speaker'],
  },
  {
    id: 'call-105',
    caller: 'Spoofed Executive Voice',
    callerPhone: '+1 (555) 019-2834',
    startTime: '2026-09-07 09:12:00',
    endTime: '2026-09-07 09:14:10',
    duration: 130,
    language: 'English',
    audioSource: 'API',
    riskScore: 88,
    riskLevel: 'HIGH_RISK',
    voiceIntegrity: 15,
    status: 'BLOCKED',
    analysisId: 'an-105',
    analysis: {
      id: 'an-105',
      callId: 'call-105',
      timestamp: '2026-09-07 09:12:00',
      syntheticProbability: 91,
      speakerSimilarity: 18,
      emotion: 'Fearful',
      emotionalConsistency: 40,
      prosodyScore: 32,
      pitchVariation: 25,
      speakingRate: 88,
      vocalEnergy: 65,
      rhythm: 35,
      stressPattern: 42,
      hesitationIndex: 72,
      pauseAnomaly: 'HIGH',
      pauseFrequency: 12,
      avgPauseDuration: 1600,
      abruptPauses: 5,
      temporalConsistency: 48,
      avgResponseLatency: 1300,
      turnTakingConsistency: 45,
      detectedLanguage: 'English',
      languageConfidence: 99,
      overallRiskScore: 88,
      riskLevel: 'HIGH_RISK',
      riskFactors: [
        'TTS Neural vocoder artifacts detected at 4kHz-8kHz',
        'Synthetic cadence and pitch quantization',
        'Impersonation target: Chief Financial Officer',
      ],
      recommendation: 'END_CALL',
      recommendationReason: 'High probability CEO voice clone financial attack.',
    },
    transcript: [
      {
        id: 'tr-40',
        timestamp: '00:06',
        speaker: 'CALLER',
        text: 'This is David from executive management. I need an urgent wire transfer executed immediately.',
        isSuspicious: true,
        anomalyNote: 'Vocoder phase alignment anomaly detected',
      },
    ],
    tags: ['CEO Fraud', 'English Deepfake'],
  },
];

export const MOCK_RISK_EVENTS: RiskEvent[] = [
  {
    id: 'evt-1',
    callId: 'call-101',
    timestamp: '2026-09-07 11:02:45',
    type: 'SYNTHETIC_VOICE',
    severity: 'HIGH_RISK',
    message: 'Hindi deepfake voice clone detected (94% synthetic score) on call from +91 99001 88219.',
    acknowledged: false,
  },
  {
    id: 'evt-2',
    callId: 'call-105',
    timestamp: '2026-09-07 09:12:30',
    type: 'SPEAKER_MISMATCH',
    severity: 'HIGH_RISK',
    message: 'CEO voice clone wire transfer attack intercepted and blocked automatically.',
    acknowledged: true,
  },
  {
    id: 'evt-3',
    callId: 'call-103',
    timestamp: '2026-09-05 14:21:10',
    type: 'PAUSE_ANOMALY',
    severity: 'SUSPICIOUS',
    message: 'Unusual latency and spectral phase jitter on Gujarati caller line.',
    acknowledged: true,
  },
];

export const MOCK_ANALYTICS: AnalyticsMetric[] = [
  { date: 'Sep 01', callsAnalyzed: 45, safeCalls: 38, suspiciousCalls: 5, highRiskCalls: 2, syntheticDetections: 2, verificationRequests: 4 },
  { date: 'Sep 02', callsAnalyzed: 52, safeCalls: 44, suspiciousCalls: 6, highRiskCalls: 2, syntheticDetections: 2, verificationRequests: 5 },
  { date: 'Sep 03', callsAnalyzed: 61, safeCalls: 51, suspiciousCalls: 7, highRiskCalls: 3, syntheticDetections: 3, verificationRequests: 6 },
  { date: 'Sep 04', callsAnalyzed: 48, safeCalls: 42, suspiciousCalls: 4, highRiskCalls: 2, syntheticDetections: 1, verificationRequests: 3 },
  { date: 'Sep 05', callsAnalyzed: 70, safeCalls: 58, suspiciousCalls: 8, highRiskCalls: 4, syntheticDetections: 4, verificationRequests: 7 },
  { date: 'Sep 06', callsAnalyzed: 55, safeCalls: 47, suspiciousCalls: 6, highRiskCalls: 2, syntheticDetections: 2, verificationRequests: 5 },
  { date: 'Sep 07', callsAnalyzed: 68, safeCalls: 54, suspiciousCalls: 9, highRiskCalls: 5, syntheticDetections: 5, verificationRequests: 8 },
];

export const LANGUAGE_DISTRIBUTION: LanguageDistribution[] = [
  { language: 'Hindi', count: 142, percentage: 35.5 },
  { language: 'English', count: 110, percentage: 27.5 },
  { language: 'Punjabi', count: 48, percentage: 12.0 },
  { language: 'Gujarati', count: 36, percentage: 9.0 },
  { language: 'Tamil', count: 28, percentage: 7.0 },
  { language: 'Telugu', count: 20, percentage: 5.0 },
  { language: 'Kannada', count: 16, percentage: 4.0 },
];

export const SIGNAL_DISTRIBUTION: SignalDistribution[] = [
  { signal: 'Neural Vocoder Phase Artifacts', contribution: 38 },
  { signal: 'Speaker Embedding Mismatch', contribution: 26 },
  { signal: 'Prosodic Pitch Flattening', contribution: 18 },
  { signal: 'Unnatural Pause Cadence', contribution: 12 },
  { signal: 'Contextual Fraud Keywords', contribution: 6 },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'ALERT',
    title: 'High Risk Call Intercepted',
    message: '94% synthetic Hindi voice clone attempt blocked on incoming line.',
    timestamp: '2026-09-07 11:02',
    read: false,
    callId: 'call-101',
  },
  {
    id: 'notif-2',
    type: 'WARNING',
    title: 'Verification Needed',
    message: 'Gujarati incoming call flagged for secondary caller identity verification.',
    timestamp: '2026-09-05 14:21',
    read: true,
    callId: 'call-103',
  },
  {
    id: 'notif-3',
    type: 'SUCCESS',
    title: 'Speaker Profile Enrolled',
    message: 'Voice print signature for Rajesh Sharma successfully registered.',
    timestamp: '2026-09-04 09:00',
    read: true,
  },
];
